schema_version: 1

context:
  name: python-mumps
  version: 0.0.4

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/python_mumps-${{ version }}.tar.gz
  sha256: 2cc81a86066641fa993b6636c4e9e11c7e03b43766ec7d01b40f2796067a665e
  patches:
    - if: target_platform == 'osx-arm64'
      then: 0001-disable-scotch.patch

build:
  number: 5
  skip: match(python, "<3.11") or python_impl == 'pypy'

outputs:
  - package:
      name: python-mumps
    requirements:
      build:
        - if: build_platform != target_platform
          then: python
        - if: build_platform != target_platform
          then: cross-python_${{ target_platform }}
        - if: build_platform != target_platform
          then: cython
        - if: build_platform != target_platform
          then: numpy
        - ${{ compiler('c') }}
        - ${{ stdlib("c") }}
        - if: unix
          then: ninja
        - if: unix
          then: pkg-config
      host:
        - python
        - cython
        - meson
        - meson-python
        - numpy
        - mumps-seq
        - setuptools-scm
        - pip
        - python-build
      run:
        - python
        - scipy >=1.11
        - mumps-seq
    
    tests:
      - python:
          imports:
            - mumps
      - requirements:
          run:
            - pip
            - pytest
        script:
          - pip check
          - python -c "import mumps; mumps.test()"
  - package:
      name: python-mumps-mpi
    build:
      skip: win
    requirements:
      build:
        - if: build_platform != target_platform
          then: python
        - if: build_platform != target_platform
          then: cross-python_${{ target_platform }}
        - if: build_platform != target_platform
          then: cython
        - if: build_platform != target_platform
          then: numpy
        - ${{ compiler('c') }}
        - ${{ stdlib("c") }}
        - if: unix
          then: ninja
        - if: unix
          then: pkg-config
      host:
        - python
        - mpi4py
        - cython
        - meson
        - meson-python
        - numpy
        - mumps-mpi
        - setuptools-scm
        - pip
        - python-build
      run:
        - python
        - mpi4py
        - scipy >=1.11
        - mumps-mpi
    
    tests:
      - python:
          imports:
            - mumps
      - requirements:
          run:
            - pip
            - pytest
        script:
          - pip check
          - python -c "import mumps; mumps.test()"          

about:
  summary: Bindings and Python interface for the MUMPS sparse solver
  license: BSD-2-Clause
  license_file: LICENSE
  homepage: https://gitlab.kwant-project.org/kwant/python-mumps

extra:
  recipe-maintainers:
    - akhmerov
